create_clock -period 10.000 -name CLK_100 -waveform { 0.000 5.000 } [get_ports CLK_100]

set_property PACKAGE_PIN AB1 [get_ports AC_ADR0]
set_property PACKAGE_PIN Y5 [get_ports AC_ADR1]
set_property PACKAGE_PIN Y8 [get_ports AC_GPIO0]
set_property PACKAGE_PIN AA7 [get_ports AC_GPIO1]
set_property PACKAGE_PIN AA6 [get_ports AC_GPIO2]
set_property PACKAGE_PIN Y6 [get_ports AC_GPIO3]
set_property PACKAGE_PIN AB4 [get_ports AC_SCK]
set_property PACKAGE_PIN AB5 [get_ports AC_SDA]
set_property PACKAGE_PIN AB2 [get_ports AC_MCLK]
set_property PACKAGE_PIN Y9 [get_ports CLK_100]

set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_ADR1]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO0]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO1]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO2]
set_property IOSTANDARD LVCMOS33 [get_ports AC_GPIO3]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SCK]
set_property IOSTANDARD LVCMOS33 [get_ports AC_SDA]

set_property IOSTANDARD LVCMOS33 [get_ports AC_MCLK]

set_property IOSTANDARD LVCMOS33 [get_ports CLK_100]
